name: 🚀 Deploy website on push

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3.4.0

      # https://github.com/actions/checkout
      - name: Checkout WP Plugin
        uses: actions/checkout@v3.4.0
        with:
          repository: XXX
          token: ${{ secrets.my_pat }}
          path: mu-plugins

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /text.dexnovate.com/
          exclude: |
            **/.git*
            **/.git*/**
            .git*
            .git*/**
            .github/*